---

  language: ruby
  rvm:
    - 1.9.3
    - 2.0.0
    - 2.1.0

  before_install:
    # Clean up production lock files
    - rm Gemfile.lock Puppetfile.lock
    # Ensure we are getting Puppet straight from source
    #- wget https://apt.puppetlabs.com/puppetlabs-release-precise.deb
    #- sudo dpkg -i puppetlabs-release-precise.deb
    #- sudo apt-get update
    #- sudo apt-get install -qy puppet facter
    # Remove warning for template_dir deprecation and hiera configuration
    #- sudo sed -ie '/template.*/d' /etc/puppet/puppet.conf
    #- sudo touch /etc/puppet/hiera.yaml
  install:
    - bundle install
    - puppet --version
    - facter --version
    - librarian-puppet install

  script:
    - #rake test
    - rake validation
